/**
* @description       : This class provides utility methods related to date operations.
* @author            : NikirDev1
* @group             : 
* @last modified on  : 17-01-2025
**/
global class DateUtility {
    /**
     * @description : Returns the current date.
     * @return      : Date The current date.
     */
    global static Date getCurrentDate() {
        return Date.today();
    }
}